apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthapp-green
  labels:
    app: healthapp
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthapp
      version: green
  template:
    metadata:
      labels:
        app: healthapp
        version: green
    spec:
      containers:
      - name: healthapp
        image: prady200545/healthapp:latest
        ports:
        - containerPort: 5000
        env:
        - name: APP_COLOR
          value: "green"
        - name: APP_VERSION
          value: "v1"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
